Models/ErrorViewModel.cs
namespace PadariaDoceAroma.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Item.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Mercadinho.Models
{
    [Table("TB_PRODUTO")]
    public class Item
    {
        [Column("cd_item")]
        public int Id { get; set; }

        [Column("nm_nome_item")]
        public String Nome { get; set; }

		[Column("vl_valor")]
		public double Valor { get; set; }

        [NotMapped]
        public Boolean Vegano { get; set; }

        [Column("ds_categoria")]
        public TipoCategoria Categoria { get; set; }


        [Column("ds_descrica")]
        public String Descricao { get; set; }
    }

}

Models/ItensPedidos.cs
/*using AspNetCore;*/
using System.ComponentModel.DataAnnotations.Schema;

namespace PadariaDoceAroma.Models
{

    [Table("TB_ITEN_PEDIDO")]
    public class ItensPedidos
    {

        // Tabela associativa 
        [Column("cd_item_pedido")]
        public int IdItemPedido { get; set; }


        // FAZER O ESQUEMA DE MANY TO ONE
        
        public int FK_Pedido { get; set; }



        public int FK_Produto { get; set; }


    }
}

Models/Pedido.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PadariaDoceAroma.Models
{
    [Table("TB_PEDIDO")]
    public class Pedido
    {

        [Column("cd_pedido"), Key()]
        public int IdPedido { get; set; }


        [Column("dt_pedido")]
        public DateTime DataPedido { get; set; }

        [Column("nm_cliente")]
        public string NomeCliente{ get; set; }

        [Column("vl_produto")]
        public double valorPedido { get; set; }

        
        public int FkItemId { get; set; }

        public Item Item { get; set; }

    }
}

Models/TipoCategoria.cs
namespace Mercadinho.Models
{
    public enum TipoCategoria
    {
        Salgado, Doce, Bebida
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mercadinho.Models;
using System.Diagnostics;

namespace Mercadinho.Controllers
{
    public class HomeController : Controller
    {
        //classe que herda de Controller,tudo que precisamos esta dentro dessa classe Controller

        public IActionResult Index()
        {   
            Item mercadinho = new Item();
            return View(mercadinho);
        }
        //Index é a nossa página principal

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Mercadinho.DataBase;
using Mercadinho.Models;

namespace Mercadinho.Controllers
{
    public class ItemController : Controller
    {
        // Para nao precisar mais usar as LISTAS
        private MercadinhoContext _context;

        // Para nao precisar mais usar as LISTAS
        public ItemController(MercadinhoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            
            var listaItens = _context.Itens.ToList();

            return View(listaItens);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Item item)
        {

            _context.Itens.Add(item);
            _context.SaveChanges();
            
            TempData["mensagem"] = "Item cadastrado!";
            
            return RedirectToAction("Cadastrar");

        }


        [HttpGet]
        public IActionResult Editar(int id)
        {

            var item = _context.Itens.Find(id);

            return View(item);
        }

        [HttpPost]
        public IActionResult Editar(Item item)
        {

            _context.Itens.Update(item);
            _context.SaveChanges();

            TempData["mensagem"] = " Item atualizado!";

            return RedirectToAction("Editar");
        }


        [HttpPost]
        public IActionResult Apagar(Item item)

        {

            _context.Itens.Remove(item);
            _context.SaveChanges();

            TempData["mensagem"] = "Item removido com sucesso!";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Pesquisar(string nomePesquisa)
        {

            var listaPesquisa = _context.Itens.Where(
                                    i => i.Nome.ToLower()
                                               .Contains(nomePesquisa.ToLower()))
                                               .ToList();

            return View(listaPesquisa);
        }

        public double PesquisaValor(int id)
        {
            var Item = _context.Itens.First(i => i.Id == id);


            return Item.Valor;
        }

        public IActionResult Resetar()
        {

            return RedirectToAction("Index");

        }

    }
}

Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mercadinho.DataBase;
using Mercadinho.Models;

namespace Mercadinho.Controllers
{
    public class PedidoController : Controller
    {

        private MercadinhoContext _context;

        private static IList<Item> _listaItens = new List<Item>();


        public PedidoController(MercadinhoContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            _listaItens = _context.Itens.ToList();
            ViewBag.Pedido = new Pedido();

            return View(_listaItens);
        }


        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Pedido pedido, int ItemId)
        {

            ItemController ItemValorPesquisa = new ItemController(_context);
            

            pedido.DataPedido = DateTime.Now;
            pedido.FkItemId =  ItemId;

            // Valor
            pedido.valorPedido = ItemValorPesquisa.PesquisaValor(ItemId);

            _context.Pedidos.Add(pedido);
            _context.SaveChanges();

            TempData["mensagem"] = "Pedido cadastrado!";

            return RedirectToAction("Index");

        }
    }
}

Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PadariaDoceAroma.styles.css" asp-append-version="true" />
</head>

<body>
    <div id="parteUm">
        <div id="container">
            <h2 class="registro">Mercadinho</h2>
            
            <a asp-controller="Item" asp-action="Cadastrar"><button class="botoes">Cadastrar Novo Item</button></a>
            <br>
            <a asp-controller="Item" asp-action="Index"><button class="botoes">Ver cardápio Cadastrado</button></a>
        </div>
        <div id="foto">
            <img id="foto_padaria" src="./img/inicio.png" alt="Foto da padaria">
        </div>
    </div>
    <h4>Mordida no Paraíso!</h4>
    <div id="containerDois">
        <div class="imagens">
            <img src="./img/pao.png" alt="Imagem de pães">
            <p class="nomeComida">Pães fofinhos</p>
            <p>Pães de Batata, mandioca e Banana</p>
        </div>
        <div class="imagens">
            <img src="./img/bolo.png" alt="Imagem de bolos">
            <p class="nomeComida">Bolos tentadores</p>
            <p>Bolos de chocolate, cenoura, laranja e limão</p>
        </div>
        <div class="imagens">
            <img src="./img/torta.png" alt="Imagem de tortas">
            <p class="nomeComida">Tortas deliciosas</p>
            <p>Tortas de creme de mirtilo, maçã, pêssego e banana</p>
        </div>
    </div>
    <footer>
        Criando memórias, uma fatia de cada vez!
    </footer>
</body>

</html>

Views/Item/Apagar.cshtml
@{
    ViewData["Title"] = "Apagar";
}

@addTagHelper *, Mercadinho

@model Item
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link rel="stylesheet" href="./css/remover.css">
</head>

<body>
    <main>

        <div id="container">
            <h3>Doce aroma</h3>
            <h2 class="registro">Você gostaria </h2>
            <h2 class="registro">de remover</h2>
            <h2 class="registro">esse item ? </h2>
            <div id="opcoes">
                <a href="./registro.html" target="_blank"> <button class="botoes">SIM</button> </a>
                <a href="./listagem.html" target="_blank"><button class="botoes">NÃO</button></a>
            </div>
        </div>
        <div id="produto">
            <h4>Nome: </h4>
            <h4>Valor: R$</h4>
            <h4>É vegano? : </h4>
            <h4>Categoria : </h4>
            <h4>Descrição: </h4>
        </div>
        </div>

    </main>

</body>

</html>

Views/Item/Cadastrar.cshtml
@model Item
@{
    ViewData["Title"] = "Cadastrar item";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar</title>
    <link rel="stylesheet" href="~/css/registro.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mercadinho.styles.css" asp-append-version="true" />
</head>
<body>
            <h5>registro de</h5>
            <h5>sabores</h5>

    <alert texto="@TempData["mensagem"]"></alert>
    <div id="container">


        <form asp-action="Cadastrar" id="formulario">
            <partial name="_Formulario" id="formulario"></partial>
            <a asp-action="Cadastrar"><button id="botao">Cadastrar</button></a>
        </form>
        <div id="foto">
            <img src="./img/bolo.png" alt="Imagem de bolos">
        </div>
    </div>
</body>
</html>

Views/Item/Editar.cshtml
@{
    ViewData["Title"] = "Editar item";
}

@addTagHelper *, Mercadinho

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar</title>
    <link rel="stylesheet" href="~/css/registro.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mercadinho.styles.css" asp-append-version="true" />
</head>
<body>
    <h5>registro de</h5>
    <h5>sabores</h5>

    <main>

        <alert texto="@TempData["mensagem"]"></alert>

        <div id="container">
            <form asp-action="Editar" id="formulario">
                <partial name="_Formulario" id="formulario"></partial>
                <button id="botaoEditar" type="submit">Editar</button>
            </form>
            <div id="foto">
                <img src="./img/bolo.png" alt="Imagem de bolos">
            </div>
        </div>
    </main>
</body>
</html>

Views/Item/Index.cshtml
@model List<Item>

@{
    ViewData["Title"] = "Listagem";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem</title>

    <link rel="stylesheet" href="~/css/listagem.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mercadinho.styles.css" asp-append-version="true" />
</head>

<body>
    <alert texto="@TempData["mensagem"]"></alert>          
            <h1>Itens Cadastrados</h1>
    @* PESQUISAR AQUI: *@
    <div id="busca">
        
        <form asp-action="Pesquisar"  method="post">

            <label >Pesquisar por nome: </label>
            <input name="nomePesquisa" id="" size="50" maxlength="50" />

            @* BOTAO PARA ACIONAR PESQUISA *@
            <a asp-action="Pesquisar" asp-route-id="campoEditar" target="_blank">
                <button type="submit" class="botoes">Pesquisar</button>
            </a>


        </form>

        <form asp-action="Resetar" method="post"> 

            @* RESETAR A PESQUISA *@
            <a asp-action="Resetar" target="_blank">
                <button type="submit" class="botoes">Resetar</button>
            </a>
        </form>
    </div>
    
    <main>
      
        @foreach (var item in Model)
        {
            <div class="produto">
                <h4>@item.Id - Nome: @item.Nome</h4>
                <h4>Valor: R$@item.Valor</h4>
                <a asp-action="Editar" asp-route-id="@item.Id" target="_blank">
                    <button class="botoes">Editar</button>
                </a>
                <button onclick="itens.value = @item.Id" type="button" class="botoes" data-bs-toggle="modal"
                        data-bs-target="#exampleModal">
                    Excluir
                </button>
            </div>
        }

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        O item deve ser excluído?
                    </div>
                    <div class="modal-footer">
                        <form asp-action="Apagar">

                            <input type="hidden" name="id" id="itens" />
                            <button type="submit" class="btn btn-danger">Sim</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
 
</body>

</html>

Views/Item/Pesquisar.cshtml
@model List<Item>

@{
    ViewData["Title"] = "Listagem";
}
<!DOCTYPE html>
<html lang="en">


    @* Reaproveitamento da pagina INDEX mas com o diferencial que o model List<Item>
        recebe a lista PERSONALIZADA dos itens FILTRADOS (PESQUISADOS) *@

    <partial name="Index" id="index"></partial>


</html>

Views/Item/_Formulario.cshtml
@model Item

<div>
    <label asp-for="Nome">NOME:</label>
    <br />
    <input asp-for="Nome" type="text" size="50" maxlength="50" required autocomplete="off">
</div>

<div>
    <label asp-for="Valor">VALOR UNITÁRIO:</label>
    <br />
    <input asp-for="Valor" type="text" size="50" maxlength="50" required autocomplete="off">
</div>

<div>
    <label asp-for="Vegano">É VEGANO?</label>
    <input asp-for="Vegano" />
</div>

<div>
    <label asp-for="Categoria">CATEGORIA</label>
    <br />
    <select asp-for="Categoria" asp-items="@Html.GetEnumSelectList<TipoCategoria>()" class="form-select">
        <option>Selecione</option>
    </select>
</div>

<div>
    <br />
    <label asp-for="Descricao">DESCRIÇÃO:</label>
    <div>
        <textarea asp-for="Descricao" rows="8" cols="54" placeholder="Explique o que torna sua comida especial!" autocomplete="off" required></textarea>
    </div>
</div>

Views/Pedido/Index.cshtml
@model List<Item>
@{
    ViewData["Title"] = "Listagem";
    
    
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem</title>

    <link rel="stylesheet" href="~/css/listagem.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mercadinho.styles.css" asp-append-version="true" />
</head>

<body>

    <alert texto="@TempData["mensagem"]"></alert>
    <h1>Realize um Pedido</h1>

@*     @foreach (var item in Model)
    {
        listaItens.Add(item.Nome);
    } *@

    <div id="container">
        <form asp-action="Cadastrar" id="formulario">


            @* _FormularioPedido aqui *@
            @* <partial name="_FormularioPedido" id="formulario"></partial> *@
            <div>
                <label for="NomeCliente">Nome Cliente:</label>
                <br />
                <input name="NomeCliente" type="text" size="50" maxlength="50" required autocomplete="off">
                
            </div>


      
                <label >Produtos</label>
                <br />
            <select name="ItemId" class="form-select">

                    @foreach (var produto in Model)
                    {

                        <option value="@produto.Id" >@produto.Nome</option>
                        @* <input name="valorItem" type="hidden" value="@produto.Valor"> *@
                    }

            </select>
            

            <a asp-action="Cadastrar">
                <button type="submit" id="botao">Cadastrar</button>
            </a>

        </form>
    </div>

</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mercadinho</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/cabecalho.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mercadinho.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Itens
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-action="Cadastrar" asp-controller="Item">Cadastrar</a></li>
                                <li><a class="dropdown-item" asp-action="Index" asp-controller="Item">Listar</a></li>
                                <li><a class="dropdown-item" asp-action="Index" asp-controller="Pedido">Pedido</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <a asp-area="" asp-controller="Home" asp-action="Index"><h3>Doce Aroma</h3></a>
            </div>
        </nav>
    </header>
    <!---Essa página retorna o cabeçalho e o footer que já vem como padrão no asp net-->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>